vars:
- params.yaml

stages:
  data_loader:
    cmd: python -m src.main --stage data_loader
    deps:
    - src/data/data_loader.py
    - ${data.raw_path}
    outs:
    - ${data.processed_path}

  feature_engineering:
    cmd: python -m src.main --stage feature_engineering
    deps:
    - src/data/feature_engineer.py
    - ${data.processed_path}
    outs:
    - data/interim/features.csv

