data:
  raw_path: data/clean/steel_energy_cleaned_V2.csv
  processed_path: data/processed/steel_energy_processed.csv

features:
  selected:
    - lagging_current_reactive.power_kvarh
    - leading_current_reactive_power_kvarh
    - lagging_current_power_factor
    - leading_current_power_factor
    - nsm
    - hour
    - dayofweek_num
    - month
    - weekstatus_Weekend
    - load_type_Maximum_load
    - load_type_Medium_load
  target: usage_kwh

train:
  # compat con DVC (aunque uses model_types)
  model_type: xgboost

  # corre varios modelos en una sola ejecución
  model_types: [xgboost, random_forest, linear_regression]

  cv_folds: 5

  xgboost:
    n_estimators: 200
    learning_rate: 0.1
    max_depth: 6
    subsample: 0.8
    colsample_bytree: 0.8
    eval_metric: rmse
    random_state: 42
    n_jobs: -1

  random_forest:
    n_estimators: 300
    max_depth: null
    min_samples_split: 2
    min_samples_leaf: 1
    max_features: null
    random_state: 42
    n_jobs: -1

  linear_regression:
    fit_intercept: true
    n_jobs: null

mlflow:
  register_model: false        # true si quieres registrar en Registry
  model_name: "steel-energy/suite"
  use_gpu: false