data:
  processed_path: data/processed/steel_energy_processed.csv
  raw_path: data/clean/steel_energy_cleaned_V2.csv
features:
  selected:
  - lagging_current_reactive.power_kvarh
  - leading_current_reactive_power_kvarh
  - lagging_current_power_factor
  - leading_current_power_factor
  - nsm
  - hour
  - dayofweek_num
  - month
  - weekstatus_Weekend
  - load_type_Maximum_load
  - load_type_Medium_load
  target: usage_kwh
mlflow:
  model_name: steel-energy/suite
  register_model: false
  use_gpu: false
train:
  cv_folds: 5
  linear_regression:
    fit_intercept: true
    n_jobs: null
  model_type: xgboost
  model_types: model_types: [random_forest, linear_regression, xgboost]
  random_forest:
    max_depth: null
    max_features: null
    min_samples_leaf: 1
    min_samples_split: 2
    n_estimators: 300
    n_jobs: -1
    random_state: 42
  xgboost:
    colsample_bytree: 0.8
    eval_metric: rmse
    learning_rate: 0.1
    max_depth: 6
    n_estimators: 200
    n_jobs: -1
    random_state: 42
    subsample: 0.8
