data:
  raw_path: data/clean/steel_energy_cleaned_V2.csv
  processed_path: data/processed/steel_energy_processed.csv

features:
  selected:
    - lagging_current_reactive.power_kvarh
    - leading_current_reactive_power_kvarh
    - lagging_current_power_factor
    - leading_current_power_factor
    - nsm
    - hour
    - dayofweek_num
    - month
    - weekstatus_Weekend
    - load_type_Maximum_load
    - load_type_Medium_load
  target: usage_kwh

train:
  model_type: xgboost
  n_estimators: 200
  learning_rate: 0.1
  max_depth: 6
  subsample: 0.8
  colsample_bytree: 0.8
  eval_metric: rmse
  random_state: 42
  cv_folds: 5
